name: Create new tag
on:
  workflow_call: 
jobs:
  deploy:
    name: Deploy to PROD
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - run: echo "‚è≥ Implantando em PROD..."
  create-tag:
    name: Create new tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create new tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: false
